[package]
name = "cli"
version = "0.1.0"
edition = "2021"


[dependencies]
log = "0.4.20"
pest = "2.7.3"
pta-ledger = { path = "../pta-ledger" }
pta-parser = { path = "../pta-parser" }
pta-types = { path = "../pta-types" }
